# Generated by Django 3.2.16 on 2022-11-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_userinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedPost',
            fields=[
                ('mypost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postapp.mypost')),
                ('academy', models.TextField()),
                ('institution', models.TextField()),
                ('professor', models.TextField()),
            ],
            bases=('postapp.mypost',),
        ),
    ]
