# Generated by Django 4.1.1 on 2022-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_advancedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='post_type',
            field=models.CharField(default='ALL', max_length=50),
        ),
    ]
