# Generated by Django 4.1.1 on 2022-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0008_mypost_post_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='img_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
